/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import client.Client;
import app.Message;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.StyledDocument;

/**
 * /**
 *
 * @author Yunus Emre Atik (yunusemre.atik@stu.fsm.edu.tr)
 */
public class Private extends javax.swing.JFrame {

    public Private ThisPrivate;
    public Thread tmr_slider;

    public Color color;
    public String private_Room_Name;
    public boolean send_File_Control = true;

    public static ArrayList emoji = new ArrayList<>();
    public static ArrayList<Integer> emoji_Nokta = new ArrayList<>();
    public static ArrayList<String> private_online_clients = new ArrayList<>();
    public static ArrayList<String> online_clients_message = new ArrayList<>();

    public int ID;
    public int friendID;
    public static int show_ID = 1;

    public Private(String myName, int myId, String friendName, int friendID, Color color, String roomName) {
        initComponents();
        ThisPrivate = this;

        ThisPrivate.setDefaultCloseOperation(Private.DISPOSE_ON_CLOSE);
        Color frameColor = new Color(0, 153, 153);
        ThisPrivate.getContentPane().setBackground(frameColor);
        ThisPrivate.addWindowListener(exitListener);

        txt_My_Name.setText(myName);
        txt_Friend_Name.setText(friendName);
        txt_My_Name.setEnabled(false);
        txt_Friend_Name.setEnabled(false);

        ThisPrivate.ID = myId;
        ThisPrivate.friendID = friendID;
        ThisPrivate.private_Room_Name = roomName;
        ThisPrivate.color = color;

        txt_myno.setText(String.valueOf(myId));
        txt_Friendno.setText(String.valueOf(friendID));

        private_online_clients.add(txt_Friend_Name.getText());
        online_clients_message.add(txt_Friend_Name.getText());
        online_clients_message.add(txt_My_Name.getText());

        lbl_Room_Name.setText("");
        lbl_Room_Name.setText(roomName);

    }
    WindowListener exitListener = new WindowAdapter() {

        @Override
        public void windowClosing(WindowEvent e) {
            int confirm = JOptionPane.showOptionDialog(
                    ThisPrivate, "Are You Sure to Close Private Chat?",
                    "Exit Confirmation", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (confirm == 0) {
                ThisPrivate.setDefaultCloseOperation(Private.DISPOSE_ON_CLOSE);
                ActionEvent evt = null;
                btn_DisconnectActionPerformed(evt);
            } else {
                ThisPrivate.setDefaultCloseOperation(Private.DO_NOTHING_ON_CLOSE);
            }

        }
    };

    private Private() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_My_Name = new javax.swing.JTextField();
        btn_Disconnect = new javax.swing.JButton();
        txt_Friend_Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPanel_Girdi = new javax.swing.JTextPane();
        lbl_File_Send = new javax.swing.JLabel();
        emoji_Smile = new javax.swing.JLabel();
        emoji_Smile_Teeth = new javax.swing.JLabel();
        emoji_Goz_Kirpma = new javax.swing.JLabel();
        emoji_Cry = new javax.swing.JLabel();
        emoji_Teeth = new javax.swing.JLabel();
        emoji_Tedirgin = new javax.swing.JLabel();
        emoji_Dead = new javax.swing.JLabel();
        emoji_Mouthless = new javax.swing.JLabel();
        emoji_Saskin = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPanel_Ekran = new javax.swing.JTextPane();
        txt_myno = new javax.swing.JTextField();
        txt_Friendno = new javax.swing.JTextField();
        lbl_Room_Name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Private Chat Room");

        txt_My_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_My_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_Disconnect.setBackground(new java.awt.Color(255, 51, 51));
        btn_Disconnect.setText("Disconnect");
        btn_Disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DisconnectActionPerformed(evt);
            }
        });

        txt_Friend_Name.setEditable(false);
        txt_Friend_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Friend_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPanel_Girdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPanel_GirdiKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(txtPanel_Girdi);

        lbl_File_Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/icon_File_Attach.png"))); // NOI18N
        lbl_File_Send.setFocusable(false);
        lbl_File_Send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_File_SendMousePressed(evt);
            }
        });

        emoji_Smile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emoji_Smile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/Emoji_Smile.png"))); // NOI18N
        emoji_Smile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emoji_SmileMousePressed(evt);
            }
        });

        emoji_Smile_Teeth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emoji_Smile_Teeth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/Emoji_Smile_Teeth.png"))); // NOI18N
        emoji_Smile_Teeth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emoji_Smile_TeethMousePressed(evt);
            }
        });

        emoji_Goz_Kirpma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emoji_Goz_Kirpma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/Emoji_Goz_Kirpma.png"))); // NOI18N
        emoji_Goz_Kirpma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emoji_Goz_KirpmaMousePressed(evt);
            }
        });

        emoji_Cry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emoji_Cry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/Emoji_Cry.png"))); // NOI18N
        emoji_Cry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emoji_CryMousePressed(evt);
            }
        });

        emoji_Teeth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emoji_Teeth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/Emoji_Teeth.png"))); // NOI18N
        emoji_Teeth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emoji_TeethMousePressed(evt);
            }
        });

        emoji_Tedirgin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emoji_Tedirgin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/Emoji_Tedirgin.png"))); // NOI18N
        emoji_Tedirgin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emoji_TedirginMousePressed(evt);
            }
        });

        emoji_Dead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emoji_Dead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/Emoji_Dead.png"))); // NOI18N
        emoji_Dead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emoji_DeadMousePressed(evt);
            }
        });

        emoji_Mouthless.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emoji_Mouthless.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/Emoji_Mouthless.png"))); // NOI18N
        emoji_Mouthless.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emoji_MouthlessMousePressed(evt);
            }
        });

        emoji_Saskin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emoji_Saskin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/Emoji_Saskin.png"))); // NOI18N
        emoji_Saskin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emoji_SaskinMousePressed(evt);
            }
        });

        txtPanel_Ekran.setEditable(false);
        jScrollPane4.setViewportView(txtPanel_Ekran);

        txt_myno.setEditable(false);

        txt_Friendno.setEditable(false);

        lbl_Room_Name.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lbl_Room_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Room_Name.setText("Room Name");
        lbl_Room_Name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_myno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lbl_Room_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_File_Send)
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_My_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txt_Friend_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Friendno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(emoji_Smile)
                        .addGap(6, 6, 6)
                        .addComponent(emoji_Smile_Teeth)
                        .addGap(6, 6, 6)
                        .addComponent(emoji_Goz_Kirpma)
                        .addGap(6, 6, 6)
                        .addComponent(emoji_Cry)
                        .addGap(6, 6, 6)
                        .addComponent(emoji_Teeth)
                        .addGap(6, 6, 6)
                        .addComponent(emoji_Tedirgin)
                        .addGap(6, 6, 6)
                        .addComponent(emoji_Dead)
                        .addGap(6, 6, 6)
                        .addComponent(emoji_Mouthless)
                        .addGap(6, 6, 6)
                        .addComponent(emoji_Saskin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Room_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_My_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_myno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_Friend_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Friendno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_File_Send)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emoji_Smile)
                    .addComponent(emoji_Smile_Teeth)
                    .addComponent(emoji_Goz_Kirpma)
                    .addComponent(emoji_Cry)
                    .addComponent(emoji_Teeth)
                    .addComponent(emoji_Tedirgin)
                    .addComponent(emoji_Dead)
                    .addComponent(emoji_Mouthless)
                    .addComponent(emoji_Saskin))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPanel_GirdiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPanel_GirdiKeyPressed
        //buraya gelince coktan degismis oluyor

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ArrayList ids = new ArrayList<>();
            ids.add(ThisPrivate.ID);
            ids.add(ThisPrivate.friendID);
            ArrayList nameInfo = new ArrayList<>();
            Message msg = new Message(Message.Message_Type.SendPrivateMessageCheck);
            nameInfo.add(txt_My_Name.getText());        //isim
            nameInfo.add(color);                        //color
            nameInfo.add(txtPanel_Girdi.getText());     //girdi
            nameInfo.add(emoji);                        //emoji
            nameInfo.add(online_clients_message);       //friend name
            nameInfo.add(show_ID);                   //showID
            nameInfo.add(ids);                          //friendID
            nameInfo.add(lbl_Room_Name.getText());      //Room Name
            nameInfo.add(0);
            msg.content = nameInfo;
            Client.Send(msg);
            emoji = new ArrayList();
            emoji.clear();
            txtPanel_Girdi.setText("");
        }
    }//GEN-LAST:event_txtPanel_GirdiKeyPressed

    private void lbl_File_SendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_File_SendMousePressed

        File[] fileToSend = new File[1];
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("Choose a file to send.");

        if (jFileChooser.showOpenDialog(ThisPrivate) == JFileChooser.APPROVE_OPTION) {
            try {
                ArrayList id = new ArrayList<>();
                id.add(ThisPrivate.friendID);
                ArrayList fileInfo = new ArrayList<>();
                Message msg3 = new Message(Message.Message_Type.SendFilePrivateCheck);
                fileToSend[0] = jFileChooser.getSelectedFile();
                fileInfo.add(fileToSend[0].getName());              //0 path

                byte[] content = Files.readAllBytes(fileToSend[0].toPath());
                fileInfo.add(content);                              //1 data

                fileInfo.add(txt_My_Name.getText());                //2 my name
                fileInfo.add(show_ID);                           //3 showID
                fileInfo.add(private_online_clients);               //4 friend names
                fileInfo.add(ThisPrivate.friendID);                 //5 App_ID
                fileInfo.add(id);                                   //6 App_ID
                fileInfo.add(lbl_Room_Name.getText());              //7 room name

                msg3.content = fileInfo;    //path,data,myname,showID,friendname,App_ID,App_ID
                Client.Send(msg3);

            } catch (IOException ex) {
                System.out.println("Dosya Göndermede Hata! (App.Java)");
            }
        }

    }//GEN-LAST:event_lbl_File_SendMousePressed

    private void emoji_SmileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_SmileMousePressed
        StyledDocument doc = txtPanel_Girdi.getStyledDocument();
        int length = doc.getLength();
        emoji.add(0);       //Smile Op Code
        emoji.add(length);
        java.net.URL imgUrl = getClass().getResource("/app/images/Emoji_Smile_Mini.png");
        txtPanel_Girdi.insertIcon(new ImageIcon(imgUrl));
    }//GEN-LAST:event_emoji_SmileMousePressed

    private void emoji_Smile_TeethMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_Smile_TeethMousePressed
        StyledDocument doc = txtPanel_Girdi.getStyledDocument();
        int length = doc.getLength();
        emoji.add(1);   //Smile Teeth Op Code
        emoji.add(length);
        java.net.URL imgUrl = getClass().getResource("/app/images/Emoji_Smile_Teeth_Mini.png");
        txtPanel_Girdi.insertIcon(new ImageIcon(imgUrl));
    }//GEN-LAST:event_emoji_Smile_TeethMousePressed

    private void emoji_Goz_KirpmaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_Goz_KirpmaMousePressed
        StyledDocument doc = txtPanel_Girdi.getStyledDocument();
        int length = doc.getLength();
        emoji.add(2);   //Smile Teeth Op Code
        emoji.add(length);
        java.net.URL imgUrl = getClass().getResource("/app/images/Emoji_Goz_Kirpma_Mini.png");
        txtPanel_Girdi.insertIcon(new ImageIcon(imgUrl));
    }//GEN-LAST:event_emoji_Goz_KirpmaMousePressed

    private void emoji_CryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_CryMousePressed
        StyledDocument doc = txtPanel_Girdi.getStyledDocument();
        int length = doc.getLength();
        emoji.add(3);   //Cry Op Code
        emoji.add(length);
        java.net.URL imgUrl = getClass().getResource("/app/images/Emoji_Cry_Mini.png");
        txtPanel_Girdi.insertIcon(new ImageIcon(imgUrl));
    }//GEN-LAST:event_emoji_CryMousePressed

    private void emoji_TeethMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_TeethMousePressed
        StyledDocument doc = txtPanel_Girdi.getStyledDocument();
        int length = doc.getLength();
        emoji.add(4);   //Teeth Op Code
        emoji.add(length);
        java.net.URL imgUrl = getClass().getResource("/app/images/Emoji_Teeth_Mini.png");
        txtPanel_Girdi.insertIcon(new ImageIcon(imgUrl));
    }//GEN-LAST:event_emoji_TeethMousePressed

    private void emoji_TedirginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_TedirginMousePressed
        StyledDocument doc = txtPanel_Girdi.getStyledDocument();
        int length = doc.getLength();
        emoji.add(5);   //Tedirgin Op Code
        emoji.add(length);
        java.net.URL imgUrl = getClass().getResource("/app/images/Emoji_Tedirgin_Mini.png");
        txtPanel_Girdi.insertIcon(new ImageIcon(imgUrl));
    }//GEN-LAST:event_emoji_TedirginMousePressed

    private void emoji_DeadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_DeadMousePressed
        StyledDocument doc = txtPanel_Girdi.getStyledDocument();
        int length = doc.getLength();
        emoji.add(6);   //Saskin Op Code
        emoji.add(length);
        java.net.URL imgUrl = getClass().getResource("/app/images/Emoji_Dead_Mini.png");
        txtPanel_Girdi.insertIcon(new ImageIcon(imgUrl));
    }//GEN-LAST:event_emoji_DeadMousePressed

    private void emoji_MouthlessMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_MouthlessMousePressed
        StyledDocument doc = txtPanel_Girdi.getStyledDocument();
        int length = doc.getLength();
        emoji.add(7);   //Mouthless Op Code
        emoji.add(length);
        java.net.URL imgUrl = getClass().getResource("/app/images/Emoji_Mouthless_Mini.png");
        txtPanel_Girdi.insertIcon(new ImageIcon(imgUrl));
    }//GEN-LAST:event_emoji_MouthlessMousePressed

    private void emoji_SaskinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoji_SaskinMousePressed
        StyledDocument doc = txtPanel_Girdi.getStyledDocument();
        int length = doc.getLength();
        emoji.add(8);   //Saskin Op Code
        emoji.add(length);
        java.net.URL imgUrl = getClass().getResource("/app/images/Emoji_Saskin_Mini.png");
        txtPanel_Girdi.insertIcon(new ImageIcon(imgUrl));
    }//GEN-LAST:event_emoji_SaskinMousePressed

    private void btn_DisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DisconnectActionPerformed
        ThisPrivate.setVisible(false);
        //App.ThisApp.same_Person_Control = 1453;
        App.ThisApp.private_Rooms.remove(this);
        App.ciktii();
        ArrayList id = new ArrayList<>();
        id.add(ThisPrivate.friendID);
        ArrayList disconnectInfo = new ArrayList<>();
        Message msg3 = new Message(Message.Message_Type.PrivateCloseCheck);
        disconnectInfo.add(private_online_clients);             //0 useless
        disconnectInfo.add(private_online_clients);             //1 useless
        disconnectInfo.add(private_online_clients);             //2 useless
        disconnectInfo.add(txt_My_Name.getText());              //3 my name
        disconnectInfo.add(private_online_clients);             //4 friend name
        disconnectInfo.add(ThisPrivate.friendID);               //5 useless
        disconnectInfo.add(id);                                 //6 friend name
        disconnectInfo.add(lbl_Room_Name.getText());            //7 room name
        msg3.content = disconnectInfo;
        Client.Send(msg3);
    }//GEN-LAST:event_btn_DisconnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Private.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Private.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Private.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Private.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Private().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Disconnect;
    public javax.swing.JLabel emoji_Cry;
    public javax.swing.JLabel emoji_Dead;
    public javax.swing.JLabel emoji_Goz_Kirpma;
    public javax.swing.JLabel emoji_Mouthless;
    public javax.swing.JLabel emoji_Saskin;
    public javax.swing.JLabel emoji_Smile;
    public javax.swing.JLabel emoji_Smile_Teeth;
    public javax.swing.JLabel emoji_Tedirgin;
    public javax.swing.JLabel emoji_Teeth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JLabel lbl_File_Send;
    public javax.swing.JLabel lbl_Room_Name;
    public javax.swing.JTextPane txtPanel_Ekran;
    public javax.swing.JTextPane txtPanel_Girdi;
    public javax.swing.JTextField txt_Friend_Name;
    public javax.swing.JTextField txt_Friendno;
    public javax.swing.JTextField txt_My_Name;
    public javax.swing.JTextField txt_myno;
    // End of variables declaration//GEN-END:variables
}
